server:
  port: 8443

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parsels
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        default_schema: public

    show-sql: true
  liquibase:
    change-log: "classpath:db/changelog/liquibase-outputChangelog.xml"